"""check

Revision ID: a8923b09bb37
Revises: 0001_schema_inicial
Create Date: 2026-07-03 04:04:32.985854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8923b09bb37'
down_revision = '0001_schema_inicial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caja_movimientos_sesion_id'), table_name='caja_movimientos')
    op.create_index(op.f('ix_caja_movimientos_caja_sesion_id'), 'caja_movimientos', ['caja_sesion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caja_movimientos_caja_sesion_id'), table_name='caja_movimientos')
    op.create_index(op.f('ix_caja_movimientos_sesion_id'), 'caja_movimientos', ['caja_sesion_id'], unique=False)
    # ### end Alembic commands ###
